spring.main.web-application-type=none
spring.main.banner-mode=off
logging.level.root=WARN

ferrum.ui.type=lanterna
ferrum.ui.music-search-provider=youtube_music
ferrum.browser.visible=false
ferrum.cache.enabled=true
ferrum.cache.directory=${user.home}/.config/ferrum/cache
ferrum.cache.search.ttl=1d
ferrum.cache.band.ttl=7d
ferrum.cache.album.ttl=30d
