# logging.level.root=WARN

ferrum.browser.visible=false
ferrum.cache.enabled=true
ferrum.cache.directory=${user.home}/.config/ferrum/cache
ferrum.cache.search.ttl=1d
ferrum.cache.band.ttl=7d
ferrum.cache.album.ttl=-1
