spring.main.banner-mode=off
logging.level.root=WARN

ferrum.ui.type=api
ferrum.ui.music-search-provider=youtube_music
ferrum.ui.language=en
ferrum.ui.theme=default
ferrum.browser.visible=false
ferrum.cache.enabled=true
ferrum.cache.directory=${user.home}/.config/ferrum/cache
ferrum.cache.search.ttl=1d
ferrum.cache.band.ttl=7d
ferrum.cache.album.ttl=30d
